[[constraint]]
  name = "github.com/gorilla/mux"
  version = "^1.6.1"

[[constraint]]
  name = "github.com/gorilla/securecookie"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/gorilla/sessions"
  version = "^1.1.0"

[[constraint]]
  name = "github.com/docker/docker"
  version = "^17.03.2-ce"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gorilla/handlers"
  version = "1.3.0"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"
